services:
  webapi:
    build:
      context: .
      dockerfile: src/CleanArchitectureTemplate.WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
